#!/usr/bin/env python
"""
Usage:
    vyu [options]

Options:
    -c CAMERA, --camera=CAMERA
        Device number of camera. On systems with a builtin camera, this will
        choose the builtin camera. Otherwise it will pick the first one it
        finds. Setting other values than 0 allows you to directly pick a
        specific camera [Default: 0]
    -s HxW, --size=HxW
        Size of the monitor display in inches [Default: 3x3]
    -f, --flipxy
        Flip x and y coordinates of the position marker.
"""
from docopt import docopt

from vyu import cli

if __name__ == '__main__':
    args = docopt(__doc__)

    if len(args['<ACTION>']) == 0:
        args['<ACTION>'] = ['monitor', 'test']

    for action in args['<ACTION>']:
        getattr(cli, action)(args)
