#!/usr/bin/env python
"""
Usage:
    vyu [options]

Options:
    -c CAMERA, --camera=CAMERA
        Device number of camera. On systems with a builtin camera, this will
        choose the builtin camera. Otherwise it will pick the first one it
        finds. Setting other values than 0 allows you to directly pick a
        specific camera [Default: 0]
"""
from docopt import docopt
import pylab as pl
import imageio

from vyu.image import image2position

if __name__ == '__main__':
    args = docopt(__doc__)
    reader = imageio.get_reader('<video{}>'.format(args['--camera']))

    fig = pl.figure()
    ax = fig.add_subplot(111)
    eyemonitor = ax.imshow(next(iter(reader)))
    position_marker = ax.plot([0], [0], '.', color='magenta')
    fig.show()
    eyemonitor.axes.figure.canvas.draw()

    for frame in reader:
        x, y = image2position(frame)

        eyemonitor.set_data(frame)
        position_marker.set_xdata([x])
        position_marker.set_ydata([y])

        eyemonitor.axes.figure.canvas.draw()
        position_marker.axes.figure.canvas.draw()  # do we need this?
